language: cpp

script:
    make main

notifications:
  webhooks:
    urls:
      https://webhooks.gitter.im/e/e9581bd95014ca2f764f
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always


matrix:
    include:
        - os: linux
          comiler: gcc
          addons:
            apt:
                sources:
                    - ubuntu-toolchain-r-test
                packages:
                    - gcc-5
                    - g++-5
          install:
            - export CXX="g++-5" CC="gcc-5"
            - export CXXFLAGS="-Os -std=c++14"
        - os: linux
          compiler: clang
          addons:
            apt:
                sources:
                    - llvm-toolchain-precise
                    - ubuntu-toolchain-r-test
                packages:
                    - clang-3.8
          install:
            - export CXX="clang++-3.8"
            - export CXXFLAGS="-Os -std=c++14"
        - os: osx
          compiler: gcc
        - os: osx
          compiler: clang