language: cpp
compiler:
 - gcc
 - clang
os:
 - linux
 - osx
script:
    make main
notifications:
  webhooks:
    urls:
      https://webhooks.gitter.im/e/e9581bd95014ca2f764f
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

language: cpp
compiler:
  - gcc
  - clang
install:
- if [[ "$CXX" = "g++" && "$TRAVIS_OS_NAME" = "linux" ]]; then export CXX="g++-5" CC="gcc-5"; fi
- if [[ "$CXX" == "clang++" && "$TRAVIS_OS_NAME" = "linux" ]]; then export CXX="clang++-3.8"; fi
- if [[ "$TRAVIS_OS_NAME" = "linux" ]]; then export CXXFLAGS="-Os -std=c++14"; else export CXXFLAGS=""; fi
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise
    packages:
    - gcc-5
    - g++-5
    - clang-3.8